name: ci

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write        

jobs:
  infra_bootstrap:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::490159260943:role/github-actions-terraform
          aws-region: eu-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"
          terraform_wrapper: false

      - name: Terraform init
        working-directory: infra
        run: terraform init

      - name: Create ECR repo (main only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: infra
        run: terraform apply -auto-approve  -no-color -var="policy_gate_image=0" -target=aws_ecr_repository.policy_gate
        
  policy:
    runs-on: ubuntu-22.04
    needs: infra_bootstrap    
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Run policy gate (non-prod default)
        run: python scripts/policy_check.py

#     - name: Log in to GHCR
#       run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

#     - name: Build and push image
#       run: |
#         IMAGE=ghcr.io/${{ github.repository }}/policy-gate:${{ github.sha }}
#         docker build -t $IMAGE .
#         docker push $IMAGE

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::490159260943:role/github-actions-terraform
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image to ECR
        run: |
          IMAGE=${{ steps.ecr.outputs.registry }}/policy-gate:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"
          terraform_wrapper: false          

      - name: Terraform fmt (check)
        working-directory: infra
        run: terraform fmt -check -diff -recursive

      - name: Terraform init
        working-directory: infra
        run: terraform init

      - name: Show backend and state summary
        working-directory: infra
        run: |
          terraform providers
          terraform state list || true

      - name: Terraform validate
        working-directory: infra
        run: terraform validate

      - name: Show image being planned
        run: echo "Planning image :- ${{ steps.ecr.outputs.registry }}/policy-gate:${{ github.sha }}"

      - name: Terraform plan
        working-directory: infra
        run: terraform plan -no-color -var="policy_gate_image=${{ steps.ecr.outputs.registry }}/policy-gate:${{ github.sha }}"

      - name: Terraform apply (main only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: infra
        run: terraform apply -auto-approve -var="policy_gate_image=${{ steps.ecr.outputs.registry }}/policy-gate:${{ github.sha }}"
